### ISSUE TITLE
Src/requirements.txt contains errors?

### ISSUE THREAD

**Issue by jylee-xidian** [LinWeizheDragon/Knowledge-Aware-Graph-Enhanced-GPT-2-for-Dialogue-State-Tracking#2]
"ERROR: Cannot install certifi==2020.6.20 and certifi==2021.5.30 because these package versions have conflicting dependencies."

**Comment by jylee-xidian** [comment]
There have many  conflicting errors like this.

**Comment by LinWeizheDragon** [comment]
The requirement file was dumped a few years ago and may have become invalid as time goes by. I suggest installing torch and transformers of the versions specified in the requirement file, and installing manually missing packages one by one. It won't take long to resolve the conflicts.
